### ISSUE TITLE
Finding a new host site

### ISSUE THREAD

**Issue by retreat-dev** [retreat-dev/retreat-dev-general#1]
We need a retreat hosting that is apprved by the retreat coworkers.

My suggestion is that if we can use the same hosting that CTM uses for their web hosting because:
1. the retreat source codes maybe have the dependencies that are related to the hosting setup.
2.  to save time to reconfigure the codes to adopt to the new environment if possible.

**Comment by retreat-dev** [comment]
Spoke with Brother Wang, if CTM is with GoDaddy for the web hosting.  It may be a considerable option for depoying the retreat codes on it.

**Comment by retreat-dev** [comment]
Based on the retreat coworker meeting, we can decide the hosting.

**Comment by retreat-dev** [comment]
The production is called "cPanel" for both GoDaddy and HostGator.

### ** GoDaddy cPanel/web hosting production page:
```
https://www.godaddy.com/hosting/web-hosting?itc=mgr_cs_cheatsheet
```

> There are 4 plans,  Economy, Deluxe, Ultimate, Maximum.
> 
> Due to the SSL, Ultimate provides 1 SSL for free for the first year even Ultimate comes unlimited websites.  Maximum include both (SSL comes with all websites, called AutoSSL). 
> 
> cPanel is allowed the user to pick and choose the PHP versioning (8.0, 7.4, 7.3, 5.6 - I think version 7 is good for us and CTM maybe use version 5).
> 
> About mail alias, GoDaddy uses MS Exchange server with the distribute group to do it.
> 
> The website has own DNS and IP assignment, ssh into host with IP and will land the user account home directory.  The resources of the host are shared with many customers.
> 
> $275.88 (from the oringal price $299.88) is for 12 month term, the discount is provided by the agent (must connect with the agent for the discount).



### ** HostGator cPanel/web hosting production page:
```
https://www.hostgator.com/web-hosting
```

> The PHP version is between 5 and 7.
> 
> Mail alias can do "one-to-one" or "one-to-many" mail forwarding.
> 
> All plans (Hatchling Plan, Baby Plan,  Business Plan) come with SSL.
> 
> It is a shared environment.
> 
> Business Plan is $5.25 per month for the 3 year term.
>

**Comment by bobcwang** [comment]
Dear MDR coworker,

If you use GoDaddy as the host, I would suggest using the website name
"MDRnj.org" (Case doesn't matter).

This name of 5 letters is still available on the website.

*Robert C. Wang*
*王春林*

**Comment by jrhshieh1** [comment]
How about just "MDR.org"? Will that be too short?

**Comment by bobcwang** [comment]
If you type "mdr.org" on your browser URL, you will see that it belongs to
some organization called "Medical Doctor Research".

Basically, it is likely that all 3-letter website names are already taken.
It has been almost 20 years since the browser was used. We are lucky to
find a 5-letter name that is still not taken.

*Robert C. Wang*
*王春林*

**Comment by retreat-dev** [comment]
Just checked with the Richmond conference meeting website and they have a quite long name:

https://christianfamilyconference.org/

**Comment by retreat-dev** [comment]
the domain name is mdrnj.org and use GoDaddy  for 2019 code and DB.

**Comment by retreat-dev** [comment]
We have finaized the web hosting with GoDaddy.
